In [1]:
import numpy as np

In [2]:
a=np.array([1,2,3,4,5])
print(a)
print(type(a))
print(a.shape)

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [3]:
b=np.array([[1],[2],[3],[4],[5]])
print(b)
print(b.shape)

[[1]
 [2]
 [3]
 [4]
 [5]]
(5, 1)


In [4]:
c=np.array([[1,2,3],[4,5,6]])
print(c)
print(c.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)


In [5]:
# Create arrays of zeros,ones
a=np.zeros((2,4))
print(a)
b=np.ones((2,4))
print(b)
# array of constants
c=np.full((3,5),3)
print(c)

#Identity matrix
c=np.eye(5)
print(c)

# Random matrix
randomMatrix=np.random.random((2,3))
print(randomMatrix)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[3 3 3 3 3]
 [3 3 3 3 3]
 [3 3 3 3 3]]
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
[[0.37115739 0.92636385 0.68298487]
 [0.33833957 0.39974028 0.4595819 ]]


In [6]:
print(randomMatrix[:,1]) # slicing

[0.92636385 0.39974028]


In [7]:
randomMatrix[1,1:]=1
print(randomMatrix)

[[0.37115739 0.92636385 0.68298487]
 [0.33833957 1.         1.        ]]


In [8]:
z=np.zeros((3,3),dtype=np.int64)
z[1,:]=5
z[:,-1]=7
print(z)

[[0 0 7]
 [5 5 7]
 [0 0 7]]


In [9]:
print(z.dtype)

int64


In [10]:
# Mathematical operations
x=np.array([[1,2],[3,4]])
y=np.array([[5,6],[7,8]])
print(np.add(x,y))

[[ 6  8]
 [10 12]]


In [11]:
print(x*y)
print(np.multiply(x,y))
print(np.divide(x,y))
print(np.sqrt(x))

[[ 5 12]
 [21 32]]
[[ 5 12]
 [21 32]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[1.         1.41421356]
 [1.73205081 2.        ]]


In [12]:
# matrix multiplication / dot products
print(x.dot(y))
print(np.dot(x,y))

[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


In [13]:
# multiplication of vectors (Scalar)
a=np.array([1,2,3,4])
b=np.array([1,2,3,4])
print(a.dot(b))

30


In [14]:
print(a)

[1 2 3 4]


In [15]:
print(sum(a))
print(x)
print(np.sum(x,axis=0)) # column sum
print(np.sum(x,axis=1)) # row sum

10
[[1 2]
 [3 4]]
[4 6]
[3 7]


In [16]:
# Stacking of arrays
print(a)
b=b**2
print(b)

[1 2 3 4]
[ 1  4  9 16]


In [17]:
print(np.stack((a,b),axis=1))
a=np.stack((a,b),axis=0)

[[ 1  1]
 [ 2  4]
 [ 3  9]
 [ 4 16]]


In [18]:
# Reshape 
print(a)
a=a.reshape((4,-1))
print(a)

[[ 1  2  3  4]
 [ 1  4  9 16]]
[[ 1  2]
 [ 3  4]
 [ 1  4]
 [ 9 16]]


NUMPY RANDOM MODULE

In [19]:
a=np.arange(10)+5
print(a)

[ 5  6  7  8  9 10 11 12 13 14]


In [20]:
np.random.seed(1)

np.random.shuffle(a)
print(a)

[ 7 14 11  9  5  8  6 12 13 10]


In [21]:
a=np.random.rand(2,3)
print(a)

[[0.38791074 0.66974604 0.93553907]
 [0.84631092 0.31327352 0.52454816]]


In [22]:
#returns values from a standatrd normal distribution
a=np.random.rand(2,3)
print(a)

a=np.random.randint(12,45,5)
print(a)

# randomly pick one element from an array
element=np.random.choice([1,56,566,763,21,56])
print(element)

[[0.44345289 0.22957721 0.53441391]
 [0.91396202 0.45720481 0.43069857]]
[42 44 34 25 21]
56


STATISTICAL FUNCTIONS IN NUMPY

In [23]:
a=np.array([[1,2,3,4],[5,6,7,8]])
print(a)
print(np.min(a))
print(np.min(a,axis=0))
print(np.min(a,axis=1))

[[1 2 3 4]
 [5 6 7 8]]
1
[1 2 3 4]
[1 5]


In [24]:
# Mean
m=np.mean(a,axis=0)
print(m)
m=np.mean(a,axis=1)
print(m)

[3. 4. 5. 6.]
[2.5 6.5]


In [25]:
c=np.array([1,4,8,7,3])
print(np.median(c))

# Mean vs Average
print(np.mean(c))

w = np.array([1,2,3,4,5])
print(np.average(c,weights=w))

4.0
4.6
5.066666666666666


In [26]:
# Standard deviation
std=np.std(c)
print(std)

# Variance
print(std**2)
print(np.var(c))

2.5768197453450252
6.640000000000001
6.640000000000001


In [30]:
x=np.array([3,5,76,7])
print(x)
print(x.shape)


[ 3  5 76  7]
(4,)


In [35]:
x=np.array([[1],[2],[3]])
print(x)
print(x.shape)
x=x.reshape((-1,))
print(x)

[[1]
 [2]
 [3]]
(3, 1)
[1 2 3]


MATRICES & TENSORS

In [42]:
# Matrix
a=np.array([[4,5,7],[6,8,9],[6,7,2]])
print(a)
print(a.shape)
a[1:,:]=2
print(a)

[[4 5 7]
 [6 8 9]
 [6 7 2]]
(3, 3)
[[4 5 7]
 [2 2 2]
 [2 2 2]]


In [45]:
# Tensor
T=np.array([[[1,2,3],[4,5,6]],[[8,9,1],[3,7,0]]])
print(T.shape)
print(T)

(2, 2, 3)
[[[1 2 3]
  [4 5 6]]

 [[8 9 1]
  [3 7 0]]]


In [48]:
# Transpose
at=np.transpose(a)
print(a)
print(at)

[[4 5 7]
 [2 2 2]
 [2 2 2]]
[[4 2 2]
 [5 2 2]
 [7 2 2]]


In [54]:
y=a.reshape((-1,1))
yt=np.transpose(y)
print(y)
print(y.shape)
print(yt)
print(yt.shape)

[[4]
 [5]
 [7]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]]
(9, 1)
[[4 5 7 2 2 2 2 2 2]]
(1, 9)


MATRIX MULTIPLICATION

In [58]:
X=np.array([[1,2,3],[4,5,6],[7,8,9]])
Y=np.array([[5,6],[0,1],[3,4]])
p=np.dot(X,Y)
print(p)

[[14 20]
 [38 53]
 [62 86]]


In [60]:
# Hadamard Product
X=np.array([[1,2,3],[4,5,6],[7,8,9]])
Y=np.eye(3)*2+1
print(X)
print(Y)
print(X*Y)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[3. 1. 1.]
 [1. 3. 1.]
 [1. 1. 3.]]
[[ 3.  2.  3.]
 [ 4. 15.  6.]
 [ 7.  8. 27.]]


NORM OF A VECTOR

In [67]:
# It is a proxy for size of a vector
x=np.array([1,-3,5,6,-8])

In [68]:
lp2=np.linalg.norm(x)
print(lp2)

11.61895003862225


In [69]:
lp1=np.linalg.norm(x,ord=1)
print(lp1)

23.0


In [70]:
lpinf=np.linalg.norm(x,ord=np.inf)
print(lpinf)

8.0


BROADCASTING

In [74]:
l=[12,3,4,54,7]
l=l**2
print(l)

TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'int'

In [75]:
l=[12,3,4,54,7]
l=np.array(l)
l=l**2
print(l)

[ 144    9   16 2916   49]


In [78]:
m=[[1,2,3,4],[5,6,7,8]]
m=np.array(m)
m=m**2
print(m)

[[ 1  4  9 16]
 [25 36 49 64]]
