In [0]:
import torch
import numpy as np

In [22]:
torch.__version__

'1.4.0'

In [23]:
x = [1,2,3]
array = np.array(x)
array

array([1, 2, 3])

In [24]:
tensor = torch.tensor(x)
tensor

tensor([1, 2, 3])

In [25]:
tensor.shape

torch.Size([3])

In [26]:
array.mean()

2.0

In [27]:
tensor.float().mean()

tensor(2.)

In [28]:
tensor = torch.randn((2,2))
tensor

tensor([[ 0.4048,  0.4481],
        [ 0.6586, -1.9995]])

In [29]:
tensor@tensor # Matrix Multiplication

tensor([[ 0.4590, -0.7147],
        [-1.0503,  4.2933]])

In [31]:
tensor = torch.tensor([1,2,3])
tensor.view((3,1)) # Reshape Operation

tensor([[1],
        [2],
        [3]])