In [2]:
import pandas as pd
import numpy as np

In [8]:
# creating a data frame
user_data={
    "MarksA":np.random.randint(1,100,5),
    "MarksB":np.random.randint(50,100,5),
    "MarksC":np.random.randint(1,100,5)
}

In [9]:
user_data

{'MarksA': array([21, 17, 78, 53, 67]),
 'MarksB': array([73, 50, 98, 92, 52]),
 'MarksC': array([85, 77, 55, 42,  9])}

In [17]:
df=pd.DataFrame(user_data,dtype='float32')
df.head(5)

MarksA  MarksB  MarksC
0    21.0    73.0    85.0
1    17.0    50.0    77.0
2    78.0    98.0    55.0
3    53.0    92.0    42.0
4    67.0    52.0     9.0

In [18]:
df.columns

Index(['MarksA', 'MarksB', 'MarksC'], dtype='object')

In [19]:
df.to_csv('marks.csv')

In [24]:
my_data=pd.read_csv('marks.csv')
my_data=my_data.drop(columns=['Unnamed: 0'])
my_data

MarksA  MarksB  MarksC
0    21.0    73.0    85.0
1    17.0    50.0    77.0
2    78.0    98.0    55.0
3    53.0    92.0    42.0
4    67.0    52.0     9.0

In [25]:
my_data.describe()

MarksA     MarksB     MarksC
count   5.000000   5.000000   5.000000
mean   47.200000  73.000000  53.600000
std    27.261695  22.113344  30.245661
min    17.000000  50.000000   9.000000
25%    21.000000  52.000000  42.000000
50%    53.000000  73.000000  55.000000
75%    67.000000  92.000000  77.000000
max    78.000000  98.000000  85.000000

In [28]:
my_data.tail(n=3)

MarksA  MarksB  MarksC
2    78.0    98.0    55.0
3    53.0    92.0    42.0
4    67.0    52.0     9.0

In [29]:
# Accessing a row
df.iloc[3]

MarksA    53.0
MarksB    92.0
MarksC    42.0
Name: 3, dtype: float32

In [30]:
# Accessing a row and column
df.iloc[3,1]

92.0

In [34]:
idx=[df.columns.get_loc('MarksB'),df.columns.get_loc('MarksC')]
print(idx)
df.iloc[3][idx]

[1, 2]


MarksB    92.0
MarksC    42.0
Name: 3, dtype: float32

In [37]:
df.iloc[:3,idx]

MarksB  MarksC
0    73.0    85.0
1    50.0    77.0
2    98.0    55.0

In [41]:
# Sort data frame
my_data

MarksA  MarksB  MarksC
0    21.0    73.0    85.0
1    17.0    50.0    77.0
2    78.0    98.0    55.0
3    53.0    92.0    42.0
4    67.0    52.0     9.0

In [44]:
my_data.sort_values(by=["MarksC","MarksA"],ascending=False)

MarksA  MarksB  MarksC
0    21.0    73.0    85.0
1    17.0    50.0    77.0
2    78.0    98.0    55.0
3    53.0    92.0    42.0
4    67.0    52.0     9.0

In [45]:
data_array=my_data.values

In [48]:
print(type(my_data))
print(data_array)
print(type(data_array))

<class 'pandas.core.frame.DataFrame'>
[[21. 73. 85.]
 [17. 50. 77.]
 [78. 98. 55.]
 [53. 92. 42.]
 [67. 52.  9.]]
<class 'numpy.ndarray'>


In [49]:
# Numpy arrays to data frame

In [53]:
new_df=pd.DataFrame(data_array,dtype='int32',columns=["Physics","Chem","Maths"])
new_df

Physics  Chem  Maths
0       21    73     85
1       17    50     77
2       78    98     55
3       53    92     42
4       67    52      9

In [56]:
new_df.to_csv("PCM.csv",index=False)

In [57]:
pcm=pd.read_csv('PCM.csv')
print(pcm)

   Physics  Chem  Maths
0       21    73     85
1       17    50     77
2       78    98     55
3       53    92     42
4       67    52      9
